// const sampleOutput = [
//     {
//         title: 'DNS Resolution',
//         icon: 'Network',
//         subSteps: [
//             'User Request',
//             'DNS Query',
//             'Recursive Query',
//             'DNS Response',
//         ],
//         position: 'above',
//         technicalTerms: [
//             'DNS',
//             'IP address',
//             'example.com',
//             'DNS server',
//             'root server',
//             'TLD server',
//             'authoritative server',
//             'cache',
//         ],
//     },
//     {
//         title: 'Establishing a Connection (TCP Handshake)',
//         icon: 'Handshake',
//         subSteps: ['SYN', 'SYN-ACK', 'ACK', 'Connection Established'],
//         position: 'above',
//         technicalTerms: [
//             'TCP',
//             'IP address',
//             'SYN',
//             'SYN-ACK',
//             'ACK',
//             'three-way handshake',
//         ],
//     },
//     {
//         title: 'Packet Creation and Fragmentation',
//         icon: 'TrendingUpDown',
//         subSteps: [
//             'HTTP Request Creation',
//             'Data Segmentation',
//             'Header Addition',
//         ],
//         position: 'above',
//         technicalTerms: [
//             'HTTP request',
//             'GET request',
//             'TCP segment',
//             'TCP header',
//             'source port',
//             'destination port',
//             'sequence numbers',
//             'IP header',
//             'source IP',
//             'destination IP',
//             'frame header',
//             'MAC address',
//             'frame trailer',
//             'Transport Layer',
//             'Network Layer',
//             'Data Link Layer',
//         ],
//     },
//     {
//         title: 'Data Link Layer & Physical Layer',
//         icon: 'Router',
//         subSteps: ['MAC Address Resolution', 'Frame Transmission'],
//         position: 'above',
//         technicalTerms: [
//             'ARP',
//             'MAC address',
//             'gateway',
//             'router',
//             'Ethernet cable',
//             'Wi-Fi',
//         ],
//     },
//     {
//         title: 'Router Processing',
//         icon: 'Router',
//         subSteps: [
//             'Frame Reception',
//             'Routing Decision',
//             'Frame Re-Encapsulation',
//         ],
//         position: 'above',
//         technicalTerms: ['IP packet', 'routing table', 'next hop'],
//     },
//     {
//         title: 'Packet Traversal Over the Internet',
//         icon: 'Share2',
//         subSteps: ['Hop-by-Hop Routing', 'Network Layers Handling'],
//         position: 'above',
//         technicalTerms: [
//             'routers',
//             'hop-by-hop routing',
//             'routing table',
//             'Data Link layer',
//         ],
//     },
//     {
//         title: 'Destination Network & Server Processing',
//         icon: 'Server',
//         subSteps: [
//             'Arrival at the Destination Network',
//             'Internal Routing',
//             'TCP Processing',
//             'HTTP Request Processing',
//         ],
//         position: 'above',
//         technicalTerms: [
//             'MAC address',
//             'TCP segments',
//             'sequence numbers',
//             'HTTP request',
//             'HTTP response',
//             'HTML',
//         ],
//     },
//     {
//         title: 'Data Link and Transport Layer Processing',
//         icon: 'Computer',
//         subSteps: ['Frame Extraction', 'TCP Reassembly'],
//         position: 'above',
//         technicalTerms: [
//             'IP packet',
//             'TCP segments',
//             'sequence numbers',
//             'HTTP response',
//         ],
//     },
//     {
//         title: 'HTTP Response Handling',
//         icon: 'Chrome',
//         subSteps: ['Data Decryption', 'Rendering the Page'],
//         position: 'above',
//         technicalTerms: [
//             'HTTPS',
//             'SSL/TLS certificate',
//             'HTML',
//             'CSS',
//             'JavaScript',
//         ],
//     },
// ];

// export { sampleOutput };
const sampleOutput = [
    {
        title: 'DNS Resolution',
        icon: 'Network',
        subSteps: [
            'User Request',
            'DNS Query',
            'Recursive Query',
            'DNS Response',
        ],
        position: 'above',
        technicalTerms: [
            'DNS',
            'IP address',
            'example.com',
            'DNS server',
            'root server',
            'TLD server',
            'authoritative server',
            'cache',
        ],
    },
    {
        title: 'Establishing a Connection (TCP Handshake)',
        icon: 'Handshake',
        subSteps: ['SYN', 'SYN-ACK', 'ACK', 'Connection Established'],
        position: 'above',
        technicalTerms: [
            'TCP',
            'IP address',
            'SYN',
            'SYN-ACK',
            'ACK',
            'three-way handshake',
        ],
    },
];

export { sampleOutput };
